[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/breeze.toml"]

[window]
option_as_alt = "Both"
# padding.x = 10
# padding.y = 10
startup_mode = "Maximized"
decorations = "buttonless"
opacity = 0.95
# blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0

[colors.cursor]
text = "#000000"
cursor = "#FEFEFE"

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[cursor]
blink_interval = 500
blink_timeout = 0
