[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/breeze.toml"]

[window]
option_as_alt = "Both"
# padding.x = 10
# padding.y = 10
startup_mode = "Maximized"
decorations = "buttonless"
opacity = 0.95
# blur = true

# [font]
# normal.family = "JetBrainsMono Nerd Font"
# normal.style = "Regular"
# size = 14.0

[font]
# Размер шрифта в пунктах
size = 14.0
builtin_box_drawing = true

# Начертание Normal (обычное)
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Thin"

# Начертание Italic (курсив)
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

# Начертание Bold (жирное)
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Начертание Bold Italic (жирное)
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular Italic"


[colors.cursor]
text = "#000000"
cursor = "#FEFEFE"

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[cursor]
blink_interval = 500
blink_timeout = 0
